### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [physphil/UnitConverterUltimate#105]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. This issue is not saying that your current logo is unsatisfactory, I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by physphil** [comment]
Hi @jbeguna04, thanks for getting in touch.  I would love any help at all in terms of logo design, I'm certainly not a designer myself and so any help is much appreciated.  Feel free to design something new!  Thanks again.

**Comment by jbeguna04** [comment]
Greetings, Here are my proposal for the project. 
![ucu](https://user-images.githubusercontent.com/35353768/41330099-fb5644da-6f03-11e8-849c-6d1dc0bfb1fb.png)
![1](https://user-images.githubusercontent.com/35353768/41330104-0098db2e-6f04-11e8-9e09-41838ec01b47.png)
![2](https://user-images.githubusercontent.com/35353768/41330113-06552fae-6f04-11e8-8866-0ec91307645b.png)
Best Regards,
-jbeguna04

**Comment by jbeguna04** [comment]
Greetings @physphil, here is the logo with background color that you requested " #3b73af". 
![image](https://user-images.githubusercontent.com/35353768/41968652-a222dcd6-7a37-11e8-811e-66e81a440dcf.png)
Hope you can choose from those. Best regards!

**Comment by jbeguna04** [comment]
![mockup11](https://user-images.githubusercontent.com/35353768/41968979-9638704c-7a38-11e8-9f58-85cee22de699.png)
![mockup111](https://user-images.githubusercontent.com/35353768/41968980-96cc2cf6-7a38-11e8-9f05-8ccddf7f3411.png)

**Comment by physphil** [comment]
Thank you so much for your help, I'd like to include this new logo in my next update!  Would you be able to provide both logos with the circular background in 1024x1024 size?  That will help me generate the assets I need.  Thank you again!

**Comment by jbeguna04** [comment]
Will I upload the files through having a Pull Request? What do you think sir?

**Comment by jbeguna04** [comment]
https://drive.google.com/open?id=1siYuRV5fUulMCpMYZQ-KJqY32rlOYGFw
Sir, Please try this link containing 1024px sizes

**Comment by physphil** [comment]
That's perfect, thank you so much!

**Comment by jbeguna04** [comment]
Do you want me to add the logo on your ReadMe file or just create a PR for your repository?

**Comment by physphil** [comment]
I can take care of updating the logo once I release the app... Thank you
for offering though, and thank you so much for the designs! I'll let you
know once it's been released 🙂

**Comment by dericke** [comment]
Is it possible for the app to use this logo as a vector? That would be more future-proof and look better on high-resolution displays.

**Comment by physphil** [comment]
Good call.  @jbeguna04 would you be able to add both logos with a transparent background as `svg`s to the Google Drive link?  Then I can add the logo to the app as a vector.  Thank you again for all your help!
