### ISSUE TITLE
New logo design for Unit Converter Ultimate

### ISSUE THREAD

**Issue by sametceylan** [physphil/UnitConverterUltimate#107]
Hello sir, my name is Samet Ceylan and I am a designer. If you want and let me, I want to design a creative logo for Unit Converter Ultimate. I want you to know that I will do it for you. I do not want any compensation. If you would like me to design and if you have any particular detail, please contact me.

**Comment by physphil** [comment]
Thanks for getting in touch, I would love to see any designs you may have!  I'm certainly not a designer and would love any help in this area.  Thanks again!
