### ISSUE TITLE
currancy issue update not on fdroid

### ISSUE THREAD

**Issue by silversparrow** [physphil/UnitConverterUltimate#114]
your app is awsome.
however.........please put the currancy issue update on Fdroid as well.
not to sarcastic but.......there are users there as well that dosent have google play......
glad to see any response.
thank you keep up the good work.

**Comment by tacsipacsi** [comment]
If I understand it correctly, it consists of two steps:
- Creating a new [tag](https://github.com/physphil/UnitConverterUltimate/tags) for the new version (I think it should be commit e205d96) – I believe that this can be done only by @physphil
- Adding the new version to the [F-Droid repo](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.physphil.android.unitconverterultimate.txt) – this can be done by anyone with a GitLab account

**Comment by silversparrow** [comment]
hi.......
a thousend apologies..........but i am just an avrage user,so beyond informing that there's not much i can do.
anyway......this app is very useful to me,so i can only hope this will be resolved.
thank you. (-:

**Comment by tacsipacsi** [comment]
It’s OK. I wrote it mainly not for you, but for anyone who wants solve this issue (including myself, as I won’t remember the exact steps in a week, either).

**Comment by physphil** [comment]
Sorry everyone, I forgot to do this in my haste to push out the latest release!  I'll tag the release now, I _believe_ that if you create a release FDroid will recognize it and pull it in... but I could be mistaken.

**Comment by tacsipacsi** [comment]
Looking at the [history](https://gitlab.com/fdroid/fdroiddata/commits/master/metadata/com.physphil.android.unitconverterultimate.txt), it has always been updated manually, so I created a [pull request](https://gitlab.com/fdroid/fdroiddata/merge_requests/3340) which will hopefully change this.

**Comment by physphil** [comment]
Amazing... thank you!

**Comment by tacsipacsi** [comment]
Version 5.3.1 is live on [F-Droid](https://f-droid.org/en/packages/com.physphil.android.unitconverterultimate/)! Version 5.3.2 didn’t appear, probably because both tags point to commit e205d96.

**Comment by silversparrow** [comment]
hi there :-)
thank you  for uploading the update to Fdroid,it corrected the currency update issue as a result.thumbs up.
BTW......
i agree with tacsipacsi.......it is version 5.3.1 not 5.3.2 like google play.....
thank you.

**Comment by tacsipacsi** [comment]
Yeah, most probably because the two versions are the same. @physphil You can either set one of these tags to another commit (if that’s possible; I’ve never worked with tags), or close this issue (I am neither the author of this issue, nor the owner of the repo, so I can’t close the it).
