### ISSUE TITLE
Add Currency value

### ISSUE THREAD

**Issue by lifranc** [physphil/UnitConverterUltimate#122]
The currency pane would be a lot more useful if it could show the actual value of currencies. I guess you could use the gold futures prices, although finding a physical currency exchanger price for 'crown gold'(22k) - the standard currency alloy - in small denomination (5 to 25 xfo) paints or truer picture.

**Comment by tacsipacsi** [comment]
It does use the current exchange rates, although based not on gold, but on euro. The exchange rates are updated regularly from the [European Central Bank’s website](https://www.ecb.europa.eu/stats/eurofxref/).

**Comment by lifranc** [comment]
Ok, Ill close this as not within scope.
