### ISSUE TITLE
suggestion to lock portrait use to avoid landscape

### ISSUE THREAD

**Issue by tempral** [physphil/UnitConverterUltimate#143]
on my android 8 phone, when I turn the device into landscape mode, the number values are freeze, they don't get update while changing units

**Comment by nettnikl** [comment]
I can confirm this on my Android 7.0 phones and on the emulator. ConversionFragment.setCheckedChanged is not beeing called after a screen rotation. Locking the screen is not a workaround I would recommend though. I'm working on a fix.
