### ISSUE TITLE
crash after clicking “Donate”

### ISSUE THREAD

**Issue by junior291492659** [physphil/UnitConverterUltimate#169]
- I have searched the history bug list, and have not found a similar bug.

- The bug was found on the latest version on google play (can be reproduced on an Android emulator 6.0 and a Redmi Note 4X phone )

- Bug: click the dot menu in the action bar, click "Donate" (same thing happens when click the "Donate" option in the "Setting" page)

  

1. On an Android emulator 6.0, it crashs. 
  reproducing video(The toast during crash in the video says something about Internet connection, I'm pretty sure that the emulator has Internet access):
  
![unit_converter 00_00_00--00_00_09](https://user-images.githubusercontent.com/44024303/66289597-b3b0cb00-e90f-11e9-8d74-ea9eae5499e3.gif)

2. On a real device(a Redmi Note 4X phone, Android 6.0), it firstly shows a loading page of "Donate" but keeps loading and after a while it still pops up a toast below as shown in the video of emulator's scenario. Then it return to the main page instead of crashing.

    loading page:

![QQ图片20191007144304](https://user-images.githubusercontent.com/44024303/66290060-db546300-e910-11e9-83a4-58b0cd9a4130.jpg)

- crash stack:
```
E : FATAL EXCEPTION: main

E : Process: com.physphil.android.unitconverterultimate, PID: 28335

E : java.lang.RuntimeException: Unable to destroy activity {com.physphil.android.unitconverterultimate/com.physphil.android.unitconverterultimate.DonateActivity}: java.lang.IllegalArgumentException: Service not registered: com.physphil.android.unitconverterultimate.iab.IabHelper$1@85df05b

E : at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)

E : at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)

E : at android.app.ActivityThread.-wrap5(ActivityThread.java)

E : at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)

E : at android.os.Handler.dispatchMessage(Handler.java:102)

E : at android.os.Looper.loop(Looper.java:148)

E : at android.app.ActivityThread.main(ActivityThread.java:5417)

E : at java.lang.reflect.Method.invoke(Native Method)

E : at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

E : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

E : Caused by: java.lang.IllegalArgumentException: Service not registered: com.physphil.android.unitconverterultimate.iab.IabHelper$1@85df05b

E : at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1044)

E : at android.app.ContextImpl.unbindService(ContextImpl.java:1337)

E : at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)

E : at com.physphil.android.unitconverterultimate.iab.IabHelper.dispose(IabHelper.java:293)

E : at com.physphil.android.unitconverterultimate.DonateActivity.onDestroy(DonateActivity.java:77)

E : at android.app.Activity.performDestroy(Activity.java:6407)

E : at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)

E : at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)

E : ... 9 more
```

It would be really appreciated to get your concern on this. Thanks.

**Comment by junior291492659** [comment]
Hello, any update on this issue?

**Comment by tingsu** [comment]
I also encountered this issue when I try to do donation. Any plan to fix this? Thanks.

**Comment by physphil** [comment]
I'm going to start working on this now. Thanks for reporting it :)

**Comment by physphil** [comment]
I've updated the donation code to use the current Google Play Billing library, and will go out in the next release. Hopefully it will fix this issue, although you will need access to the Play Store and Google Play Services on your device in order to donate.
