### ISSUE TITLE
The “reverse” floating button disapperas when srcoll up in some fully-content pages

### ISSUE THREAD

**Issue by junior291492659** [physphil/UnitConverterUltimate#170]
- I have searched the history bug list, and have found a same bug https://github.com/physphil/UnitConverterUltimate/issues/126.

- The bug was found on the latest version on google play (can be reproduced on an Android emulator 6.0, a Redmi Note 4X phone, Android 6.0 and a Google Pixel 3 phone, Android 9.0)

- Steps to reproduce:
  
  1. Select a dimension with more units than fit on the screen (e.g. volume)

  2. Scroll up: the floating button disappears

The only way to make it re-appear is to rotate the device to landscape mode or re-select the dimension from the slide-in menu or simply scroll down.

- reproducing video:

![unit_converter2 00_00_00--00_00_17](https://user-images.githubusercontent.com/44024303/66291049-633b6c80-e913-11e9-90d5-61c5cc7746ca.gif)

The same issue mentioned above is closed and the bug seems not to be fixed in the latest version on google play. And this can be troublesome when users want to use the "reverse" function towards the units below. 
It would be really appreciated to get your concern on this. Thanks.

**Comment by tingsu** [comment]
I also encouter this issue. In this case, I cannot use the reverse functionality.

**Comment by tingsu** [comment]
I inspected the fix of issue #126. I saw the current logic will hide the FAB button when the user scroll down the list, and show the FAB button when the user scroll up the list. 

Although this solution does fix #126, I feel the user experience become a bit wierd and uncomfortable in some situations. Let me explain a bit more.

Case I:  I scroll down to the end of the list, and select two units at the bottom (i.e., the last row). Now, if I want to reverse the unit convertion, I have to scroll up until the FAB button appears, and then I could click the FAB button.

Case II: In case I, if I want to alert one of selected units, I have to scroll down to the bottom again, and scroll up again to do another convertion. It is troublesome.

I feel these two cases lower down the user experience especially when the list is long (cannot fully display on the screen, e.g., Volume) and the device's screen is small. Is it poossible to fix this issue by always keeping the FAB there? 

Anyway, thanks a lot for building this useful app!

**Comment by sjl872964789** [comment]
Hi, thanks for your amazing app, this issue is similar to the problem I was going to ask, any plan to fix this?

**Comment by oraluben** [comment]
Hi @physphil , would you take a look at this issue? I think currently behavior makes less sense than let the button to be presented all the time.

**Comment by shao-hua-li** [comment]
This app is very useful, and I like it! I feel the issue mentioned here is reasonable. If improved, it will be more convenient for users to use especially when the list is long and cannot show fully in the screen.

**Comment by tingsu** [comment]
Is this an issue? or, any plan to enhance this ?

**Comment by physphil** [comment]
So when I initially implemented that FAB behaviour a few years ago, it was standard for it to disappear while scrolling vertically.  But it looks like that pattern has fallen out of favour recently, so I'll take a look at this after #169 😄

**Comment by junior291492659** [comment]
Thanks for your reply for issue 169 and issue 170. It is a little bit inconvenient for users for it dissapears when scroll even though it is correct behavior according to standard. But I would really appreaciate it if you could improvise and improve it in this scenario.

improvise
--

**Comment by physphil** [comment]
Will go out in next release.

**Comment by tingsu** [comment]
Nice, thanks for your fixing!
