### ISSUE TITLE
Issue with bright color theme

### ISSUE THREAD

**Issue by mueller-ma** [physphil/UnitConverterUltimate#21]
When changing the color theme to bright the top right hand menu and the "switch units" button still have a dark background

![bright-color-bug](https://cloud.githubusercontent.com/assets/22525368/19828047/433dd0d0-9dbc-11e6-8eb1-66cfda825ae3.png)

**Comment by physphil** [comment]
That's no good... I'll take care of it

**Comment by mueller-ma** [comment]
Additional information:
Android 6.0.1
Oneplus X
App v4.2 from F-droid

**Comment by physphil** [comment]
Will be fixed in v5.2

**Comment by mueller-ma** [comment]
@physphil The fab is still dark
