### ISSUE TITLE
Currency Converter API Down (Again)

### ISSUE THREAD

**Issue by elydpg** [physphil/UnitConverterUltimate#232]
From the [ECB website](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html):

> Please note that [Croatia adopted the euro](https://www.ecb.europa.eu/euro/changeover/croatia/html/index.en.html) on 1 January 2023. The Croatian kuna has therefore been removed from the ECB’s list of euro foreign exchange reference rates and has not been replaced in the list by another currency.

As such, the app behaviour described in #222 has started happening again

**Comment by physphil** [comment]
Thanks so much for reporting this. I'll make it a priority to address it ASAP, hopefully in such a way that this won't keep happening if the API changes.
