### ISSUE TITLE
Bug convertir metros a kilómetros

### ISSUE THREAD

**Issue by Oxicode** [physphil/UnitConverterUltimate#35]

**Comment by physphil** [comment]
Can you please provide more information?

**Comment by Oxicode** [comment]
![screenshot_20161122-182706](https://cloud.githubusercontent.com/assets/1320709/20546202/d0e0e6ec-b0e1-11e6-98d8-4dc4eb449e58.png)
![screenshot_20161122-182659](https://cloud.githubusercontent.com/assets/1320709/20546203/d1b06f20-b0e1-11e6-8c82-e08ef896acc6.png)

**Comment by physphil** [comment]
Thanks for reporting this, but you just need to change the number of decimals to display in the settings menu.

![screenshot_20161123-110213](https://cloud.githubusercontent.com/assets/2634238/20569011/8dafed06-b16c-11e6-9790-4b8805e46f46.png)
