### ISSUE TITLE
Keyboard does not close when opening the menu

### ISSUE THREAD

**Issue by racedaemon** [physphil/UnitConverterUltimate#4]
The keyboard does not close when the cursor is inside one of the numeric fields and the user presses the menu button. But it changes from numeric input to normal input.

**Comment by physphil** [comment]
Ah yes, that won't do.  I'll take a look into it, cheers.

What device / Android version are you using?

**Comment by racedaemon** [comment]
Moto G 1st gen with stock Android 5.1.
Have fun debugging. Thanks for the useful app!

**Comment by A-bahattab** [comment]
Im trying to hide the keyboard when i pressed menu button but fail, any idea that will help me?

**Comment by physphil** [comment]
Fixed in release 4.1
