### ISSUE TITLE
Have app language settings separate from system language

### ISSUE THREAD

**Issue by benedictleejh** [physphil/UnitConverterUltimate#45]
For various reasons, some people might choose to use apps in a different language from their system language, and making people change their system language just to use an app in a certain language is not the most user-friendly thing to do.

As such, it would be nice if people could select the language the app is in separate from the system language; defaulting to the system language in the absence of a language choice feels appropriate to me.

**Comment by physphil** [comment]
A few people have asked for this - it'll be the next thing I work on!

**Comment by physphil** [comment]
Will be released in 5.3 :)
