### ISSUE TITLE
The traduction for Spanish is wrong

### ISSUE THREAD

**Issue by arielrcr** [physphil/UnitConverterUltimate#58]
The traduction for Spanish is wrong, for example:
In program is "minuta" but should be "minuto".
The same way with:
"segunda" should be "segundo".

**Comment by Arregi** [comment]
I can confirm this, the translation should be as arielrcr says. Anyway It's
a minor issue.

Kind regards

**Comment by physphil** [comment]
@arielrcr @Arregi Thanks for letting me know.  If you'd like to create a pull request with the corrections, I'd be happy to accept it!

**Comment by Arregi** [comment]
Done!
