### ISSUE TITLE
Error:(34, 0) D:\AnrdoidApps\UnitConverterUltimate\app\keystore.properties (The system cannot find the file specified)

### ISSUE THREAD

**Issue by A-bahattab** [physphil/UnitConverterUltimate#6]
Error:(34, 0) D:\AnrdoidApps\UnitConverterUltimate\app\keystore.properties (The system cannot find the file specified)
<a href="openFile:D:\AnrdoidApps\UnitConverterUltimate\app\build.gradle">Open File</a>

I delete it the block only and the line ....release and it's works fine

**Comment by physphil** [comment]
Yes, you'll need to create your own keystore.properties file in order to create a release build.  Mine is missing as it contains my own private keystore information :)
